Drop dbg! in ergoscript-compiler too
debug_tree must be defined only for test build since otherwise it trips
dead_code lint:

> error: associated function is never used: `debug_tree`